In [1]:
#k-fold cross validation 

In [9]:
from sklearn.linear_model import LogisticRegression 
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier 
import numpy as np 
from sklearn.datasets import load_digits
digits=load_digits() 

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=.3)

In [11]:
model1=LogisticRegression()
model1.fit(x_train,y_train)
model1.score(x_test,y_test) 

C:\Users\Document\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [12]:
model2=SVC()
model2.fit(x_train,y_train)
model2.score(x_test,y_test) 

0.9925925925925926

In [13]:
model3=RandomForestClassifier()
model3.fit(x_train,y_train)
model3.score(x_test,y_test)  

0.9833333333333333

In [14]:
from sklearn.model_selection import KFold 
kf=KFold(n_splits=3)
kf
 

KFold(n_splits=3, random_state=None, shuffle=False)

In [15]:
for train_index,test_index, in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index) 

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [16]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test) 

In [17]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

C:\Users\Document\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [18]:
get_score(SVC(),x_train,x_test,y_train,y_test) 

0.9925925925925926

In [19]:
get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test) 

0.9777777777777777

In [20]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [21]:
score_l=[]
score_svm=[]
score_rf=[] 
for train_index,test_index, in kf.split(digits.data):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],\
                                  digits.target[train_index],digits.target[test_index] 
    score_l.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test)) 
    score_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)) 
    

C:\Users\Document\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Document\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n

In [22]:
score_l  

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [23]:
score_rf

[0.9348914858096828, 0.9465776293823038, 0.9215358931552587]

In [24]:
score_svm 

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [25]:
from sklearn.model_selection import cross_val_score  


In [26]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\Document\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Document\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [27]:
cross_val_score(SVC(), digits.data, digits.target) 

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [28]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.93055556, 0.9       , 0.96657382, 0.9637883 , 0.91643454])

In [29]:
#exercise 

In [30]:
from sklearn.datasets import load_iris 
iris=load_iris()

In [31]:
iris.data 

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [32]:
iris.target 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [33]:
from sklearn.model_selection import KFold 
kf=KFold(n_splits=3) 
kf 

KFold(n_splits=3, random_state=None, shuffle=False)

In [34]:
from sklearn.linear_model import LogisticRegression 
mod1=LogisticRegression() 
mod1.fit(iris.data,iris.target) 


C:\Users\Document\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [35]:
mod1.score(iris.data,iris.target) 

0.9733333333333334

In [36]:
from sklearn.svm import SVC 
mod2=SVC()
mod2.fit(iris.data,iris.target) 
mod2.score(iris.data,iris.target) 


0.9733333333333334

In [37]:
from sklearn.ensemble import RandomForestClassifier
mod3=RandomForestClassifier()
mod3.fit(iris.data,iris.target)
mod3.score(iris.data,iris.target) 


1.0

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=.3)

In [39]:
mod1.fit(x_train,y_train) 

C:\Users\Document\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [40]:
mod1.score(x_test,y_test) 

0.9333333333333333

In [41]:
mod2.score(x_test,y_test) 

0.9555555555555556

In [42]:
mod3.score(x_test,y_test) 

1.0

In [43]:
from sklearn.model_selection import cross_val_score  


In [50]:
l_score=cross_val_score(LogisticRegression(),iris.data,iris.target)

C:\Users\Document\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [47]:
s_score=cross_val_score(SVC(),iris.data,iris.target) 

In [51]:
np.average(s_score)

0.9666666666666666

In [54]:
np.average(l_score)  

0.9733333333333334

In [57]:
rf_score=cross_val_score(RandomForestClassifier(),iris.data,iris.target)  
rf_score 

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [59]:
np.average(rf_score) 

0.96

In [61]:
from sklearn.tree import DecisionTreeClassifier 



In [63]:
df_score=cross_val_score(DecisionTreeClassifier (),iris.data,iris.target)
df_score 

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [64]:
np.average(df_score)

0.9533333333333334