In [13]:
import pandas as pd 
import numpy as np 
from sklearn import linear_model
import matplotlib.pyplot as plt 
home_prices=pd.read_csv("homeprices.csv")

In [14]:
home_prices 

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [15]:
home_prices.bedrooms.median() 

4.0

In [16]:
home_prices=home_prices.fillna(home_prices.bedrooms.median())
home_prices 

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [17]:
#create linear regression data model 
reg=linear_model.LinearRegression()
reg.fit(home_prices.drop('price',axis=1),home_prices.price) 

LinearRegression()

In [18]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [19]:
reg.predict([[2500,4,5]]) 

array([578876.03748933])

In [20]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [21]:
reg.intercept_ 


221323.00186540384

In [ ]:
#exercise  


In [8]:
import pandas as pd 
import numpy as np 
from sklearn import linear_model
import matplotlib.pyplot as plt 

hiring=pd.read_csv("C:\\Users\\Document\\OneDrive\\Documents\\csv files\\hiring.csv")

In [9]:
hiring 

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [10]:
hiring.experience=hiring.experience.fillna('zero')
hiring 

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [13]:

hiring.experience=hiring.experience.apply(w2n.word_to_num)  

In [43]:
!pip install word2number 

In [12]:
from word2number import w2n

In [14]:
hiring  

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [45]:
import math 
median_test_score=math.floor(hiring['test_score(out of 10)'].mean())
median_test_score

7

In [46]:
hiring['test_score(out of 10)']=hiring['test_score(out of 10)'].fillna(median_test_score)

In [47]:
hiring 

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [50]:
#create model 
reg=linear_model.LinearRegression()
reg.fit(hiring[['experience','test_score(out of 10)','interview_score(out of 10)']],hiring['salary($)']) 

LinearRegression()

In [52]:
reg.predict([[2,9,6]]) 

array([53713.86677124])

In [54]:
reg.predict([[12,10,10]]) 

array([93747.79628651])

In [56]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [58]:
reg.intercept_ 

14992.65144669314